name: Deploy DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get major of current tag and previous tag
        id: tags
        run: |
          git fetch -a
          echo "LATEST_TAG=$(git tag --sort "-committerdate" | cut -d$'\n' -f1)" >> $GITHUB_ENV
      - name: Build and deploy
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          docker build --build-arg VERSION=$LATEST_TAG -t test .
          echo "$(docker run test)"
        