name: Deploy PRD

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo $GITHUB_REF_NAME
          docker build --build-arg VERSION=${GITHUB_REF##*/} -t test .
          echo "$(docker run test)"

    