name: Deploy PRD

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${GITHUB_REF##*/}
          docker build --build-arg VERSION=${GITHUB_REF##*/} -t test .
          echo "$(docker run test)"
